apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-app
  namespace: dev
  labels:
    app: devsecops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops-app
  template:
    metadata:
      labels:
        app: devsecops-app
    spec:
      serviceAccountName: devsecops-sa
      containers:
        - name: devsecops-app
          image: nginx:latest # Replace with your Docker Hub image if needed
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: devsecops-service
  namespace: dev
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: devsecops-app
